# Site Build Settings

url:                 https://mqueiroz.me
favicon:             favicon.ico
title:		           Matheus Queiroz
tagline:             ''
description:	       ''
author:              Matheus Queiroz
timezone:            America/Sao_Paulo

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:slug
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# jekyll-paginate configuration
paginate:            5
paginate_path: /page/:num/

# jekyll-seo-tag
author:
  name: Matheus Queiroz
  twitter: mqueiroz1995
twitter:
  username: mqueiroz1995
  card: summary_large_image
social:
  name: Matheus Queiroz
  links:
    - https://github.com/mqueiroz1995
    - https://twitter.com/mqueiroz1995
    - https://www.linkedin.com/in/mmelloqueiroz/

include:
  - robots.txt

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

# excludes posts bundled in theme
exclude: [
  '_posts/2013-04-04-about-the-author.md',
  '_posts/2013-10-10-learning-resources',
  '_posts/2014-01-01-text-formatting-examples.md',
  '_posts/2015-10-10-getting-started.md',
  '_posts/2016-01-01-welcome-to-lagrange.md'
]