# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Matheus Queiroz'
description:	       'Home'
author:              'Matheus Queiroz'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

# excludes posts bundled in theme
exclude: [
  '2013-04-04-about-the-author.md',
  '2013-10-10-learning-resources',
  '2014-01-01-text-formatting-examples.md',
  '2015-10-10-getting-started.md',
  '2016-01-01-welcome-to-lagrange.md'
]